PX4/pyulog

- setup.py
This is a fix for #21. The line to fix it is this : 'ulog2kml=pyulog.ulog2kml:main' and it's added to setup.py.
> Fixed ulog2kml by adding line to setup.py

- README.md
@bkueng The url in the documentation seems to be outdated. Fixed here.
> [Tiny PR] Update url to point to correct documentation

- pyulog/info.py
Enables displaying individual messages, e.g. `boot_console_output`.
> ulog_info: add --message and --newline arguments to show a single info multi message

- pyulog/params.py
Outputs changed parameters and their timestamps in csv. This is just one way to format this -- open to other ideas. "0" is used as the timestamp for the initial parameter.
resolves #26 
Output in the csv formatted like this:
| column 1      | column 2      | column 3      | column 4      |
| ------------- | ------------- | ------------- | ------------- |
| PARAM 1       | init val      | changed val 1 | changed val 2 |
| timestamp     | 0             | timestamp 1   | timestamp 2   |
| PARAM 2       | init val      | changed val 1 | changed val 2 |
| timestamp     | 0             | timestamp 1   | timestamp 2   |
Ex. sample output from a ulog:
| column 1         | column 2         | column 3         | column 4         |
| ---------------- | ---------------- | ---------------- | …
> params: output changed parameter timestamps in csv

- pyulog/core.py
- pyulog/extract_gps_dump.py
- pyulog/info.py
- pyulog/messages.py
- pyulog/params.py
- pyulog/ulog2csv.py
- pyulog/ulog2kml.py
Fixes #38 
@bkueng I do not much like setting the static variable in the __init__ fn, but the alternative I see is passing parameters everywhere till they reach _parse_string() which is ugly as well.
> Parametrize string parsing error handling

- pyulog/params.py
Added an option to `ulog_params` to output in the same format as QGC: 
**Vehicle-ID** -- **Component-ID** -- **Name** -- **Value** -- **Type** delimited with tabs.
This allows parameter files to be pulled from logs, and subsequently `diff`ed or uploaded.
@bkueng @jgoppert
> QGC compatible formatting for `ulog_params`

- pyulog/__init__.py
- pyulog/ulog2kml.py
After running VTOL flight tests, the ulog2kml command doesn't work due to the fact that a flight mode number is 15 exceeding the length of the default color array.
Added 6 more colors to the array to fix it and be able to run ulog2kml on any .ulg file
Also added ulog2kml and ulog2csv to __init__ for easier importing from other modules.
> Added more options to the default color array.

- pyulog/extract_gps_dump.py
Hi,
I have opened PR https://github.com/PX4/PX4-Autopilot/pull/16258 in PX4 firmware, that adds support of gps_dump from multiple GNSS recievers. This PR adds support for multiple receivers in the `gps_dump`.
I added a new launch parameter `-i` that specifies the receiver instance. `-i 0` (default) exports dump of main (first) reciever. 
I have also reneamed original parametr `-i` to `-x`. It is parametr that: 'Ignore string parsing exceptions'
> Add support of multiple GNSS recievers in gps_dump messages

- pyulog/core.py
- pyulog/extract_gps_dump.py
This PR solves two of the three problems with CI. Fixes an issue on version 3.4 and 3.5 where there was an unnecessary break in the `if` and `elif` functions and `exit()` instead of `sys.exit()`.
In version 2.7 there is still issue
```
E: 88,12: Assigning to function call which doesn't return (assignment-from-no-return)
```
from line:
```python
pitch = np.arcsin(2.0 * (q[0] * q[2] - q[3] * q[1]))
```
It can be related to pylint bug: https://github.com/PyCQA/pylint/issues/2694
But will python 2.7 be further supported? Official support of python 2.x ends on January 1.
> Fix CI issues

- pyulog/params.py
Removing this must have been an accident! 
https://github.com/PX4/pyulog/issues/53#issuecomment-665595765
Note a new arg 'default' was added which now uses -d, so I made it -l instead :shrug:
> Add back delimiter argument

- README.md
- pyulog/ulog2rosbag.py
- setup.py
To streamline the logging capabilities, we considered converting the PX4 ulg files to rosbags to have a common way to display log files (for ROS1 / PX4). The conversion was easy as every uORB topic has a ROS1 msg type  defined in `px4_msgs`.
Example call:
```
ulog2rosbag ~/Documents/Logs/log_29_2021-9-3-16-43-10.ulg test.bag
```
> add ulg to rosbag script

- setup.py
The URL on https://pypi.org/project/pyulog/ is currently a broken link.
> setup.py: Fix a broken link on the PyPI page

- pylintrc
- pyulog/core.py
- pyulog/params.py
- pyulog/ulog2kml.py
Suddenly pylint started complaining about old code, seems likely it was due to a pylint ugrade. I fixed the complaints.
I searched for "except " and "except:" in the code, but couldn't find any place where changing from Exception to TypeError/KeyError/ValueError would pose a problem.
> ci: fix pylint complaints

- pyulog/px4.py
Previously, the add_roll_pitch_yaw function only added roll, pitch and yaw to four predefined messages types. This commit allows the developer to specify additional messages, which depends on the topics logged by the specific PX4 version and configuration.
> px4: add roll/pitch/yaw to arbitrary messages

- pyulog/core.py
When `value_type` is uint8_t[, the `value` is already a bytearray, so `data` can be directly extended.
Resolves https://github.com/PX4/pyulog/issues/81 .
> fix a problem with saving ulogs [issue #81]

- pyulog/core.py
- pyulog/info.py
- allow data to include padding bytes at the end (and just strip them)
- report file corruption if the size is not within expected bounds
- ulog_info: report corrupted file
> improve checks for subscription data size

- .gitignore
- pyulog/db.py
- test/test_db.py
- test/test_px4.py
Fixes https://github.com/PX4/pyulog/issues/84 , see commit message for details
> Add dataset caching for DatabaseULog

- pyulog/core.py
- pyulog/db.py
- pyulog/sql/pyulog.4.sql
- pyulog/sql/pyulog.5.sql
- test/test_db.py
- test/test_ulog.py
Calling DatabaseULog.write_ulog didn't work before, now it does.
I guess the comparison commit isn't directly related to DatabaseULog writing, but I included it since it made the write_ulog tests a little more understandable.
I noticed some indexes in the DB were missing from a previous migration so I added them too
> Support writing DatabaseULog to file

- pyulog/core.py
- test/test_ulog.py
Previously only writing to files was possible. It's useful to be able to write to BytesIO for e.g. returning generated ULog files over HTTP without having to write an intermediary file.
> core: support writing ulog to bytes handle

- pyulog/db.py
- test/test_db.py
Since we tend to allow filenames and file handles interchangably in this code base, we might run into the edge case of a closed file handle being input to calc_sha256sum. We should then open the file before getting the hash.
> fix: allow closed file handles in calc_sha256sum

- pyulog/core.py
Same as https://github.com/PX4/pyulog/pull/95 but with fixed CI since it seems the original author might not fix it
> Enable correct exporting of char data but with passing CI

- pyulog/extract_gps_dump.py
Whenever the condition `if msg_len & (1<<7)` is true, the extraction of the GPS dump fails with the following error:
```
Creating files log_7_2026-2-15-03-23-04_0_to_device.dat and log_7_2026-2-15-03-23-04_0_from_device.dat
Traceback (most recent call last):
File "/home/alex/.local/bin/ulog_extract_gps_dump", line 8, in <module>
sys.exit(main())
File "/home/alex/.local/lib/python3.10/site-packages/pyulog/extract_gps_dump.py", line 86, in main
msg_len = msg_len & ~(1<<7)
```
This is due to python trying to cast  `~(1<<7)` to a `np.uint8` as `msg_len` is a `np.uint8`. This will fail as python first does the shift and invert in its own signed int, causing a negative result, which can't be casted to an unsigned value.
The shift and invert are done with a `np.uint8` so all math is done …
> Fix GPS msg_len overflow

- pyulog/core.py
I was unable to run PX4 estimator replay with a ulog written by pyulog, due to mismatching message formats. 
To reproduce, run `pyulog.ULog(filename).write_ulog(out_filename)` with a replayable ulog in and attempt to replay the written ulog. This will fail because PX4 expects single-byte padding as `uint8_t[1]` arrays, but pyulog writes every field with length one as a scalar type.
This PR fixes that by differentiating between scalar fields and arrays with length one.
As far as I can see, the [ulog file format](https://docs.px4.io/main/en/dev_log/ulog_file_format.html) does not forbid one-wide arrays, so it makes sense for pyulog to support it.
> Write support for arrays with length one

- .github/workflows/deploy.yml
- MANIFEST.in
- pyproject.toml
- setup.py
According to https://github.com/vllm-project/vllm/pull/17389
Should be a fix for https://github.com/PX4/pyulog/issues/115
> fix pyproject.toml: require setuptools>=77.0.3
